### ISSUE TITLE
How to run backend service

### ISSUE THREAD

**Issue by Benyjuice** [alagoutte/smartcapwap#2]
I'm confused about how to run the backend server. I'm try to use php-soap with the .wsdl file in folder webservice, but failed and get the error message `Unable to join with Backend Server`

**Comment by alagoutte** [comment]
Hi Benyjuice !

but I'm no the author for smartcapwap (it is a only my fork)
You need to see https://bitbucket.org/vemax78/smartcapwap

**Comment by Benyjuice** [comment]
Thank you for your reply. I have found the backend service's php files.

**Comment by imuneer** [comment]
@Benyjuice Can you please share the backend service's php files? Thanks a lot.

**Comment by 6ang996** [comment]
please share the backend service's php files? the link can not open https://bitbucket.org/vemax78/smartcapwap

**Comment by 6ang996** [comment]
> Thank you for your reply. I have found the backend service's php files.

Hi,Can you provide backend service's php files
